package com.flinkbooking.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Represents a booking suggestion generated by the system
 */
public class BookingSuggestion implements Serializable {
    
    private String userId;
    private String suggestionId;
    private String destination;
    private List<String> recommendedHotels;
    private Double averagePrice;
    private Double averageRating;
    private String preferredRoomType;
    private String suggestionReason;
    private String timestamp;
    private Double confidenceScore;
    
    // Default constructor
    public BookingSuggestion() {}
    
    // Constructor
    public BookingSuggestion(String userId, String destination, 
                           List<String> recommendedHotels, Double averagePrice, 
                           Double averageRating, String preferredRoomType, 
                           String suggestionReason, Double confidenceScore) {
        this.userId = userId;
        this.destination = destination;
        this.recommendedHotels = recommendedHotels;
        this.averagePrice = averagePrice;
        this.averageRating = averageRating;
        this.preferredRoomType = preferredRoomType;
        this.suggestionReason = suggestionReason;
        this.confidenceScore = confidenceScore;
        this.timestamp = LocalDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME);
        this.suggestionId = generateSuggestionId();
    }
    
    private String generateSuggestionId() {
        return "SG_" + System.currentTimeMillis() + "_" + userId;
    }
    
    // Getters and Setters
    public String getUserId() { return userId; }
    public void setUserId(String userId) { this.userId = userId; }
    
    public String getSuggestionId() { return suggestionId; }
    public void setSuggestionId(String suggestionId) { this.suggestionId = suggestionId; }
    
    public String getDestination() { return destination; }
    public void setDestination(String destination) { this.destination = destination; }
    
    public List<String> getRecommendedHotels() { return recommendedHotels; }
    public void setRecommendedHotels(List<String> recommendedHotels) { this.recommendedHotels = recommendedHotels; }
    
    public Double getAveragePrice() { return averagePrice; }
    public void setAveragePrice(Double averagePrice) { this.averagePrice = averagePrice; }
    
    public Double getAverageRating() { return averageRating; }
    public void setAverageRating(Double averageRating) { this.averageRating = averageRating; }
    
    public String getPreferredRoomType() { return preferredRoomType; }
    public void setPreferredRoomType(String preferredRoomType) { this.preferredRoomType = preferredRoomType; }
    
    public String getSuggestionReason() { return suggestionReason; }
    public void setSuggestionReason(String suggestionReason) { this.suggestionReason = suggestionReason; }
    
    public String getTimestamp() { return timestamp; }
    public void setTimestamp(String timestamp) { this.timestamp = timestamp; }
    
    public Double getConfidenceScore() { return confidenceScore; }
    public void setConfidenceScore(Double confidenceScore) { this.confidenceScore = confidenceScore; }
    
    @Override
    public String toString() {
        return "BookingSuggestion{" +
                "userId='" + userId + '\'' +
                ", suggestionId='" + suggestionId + '\'' +
                ", destination='" + destination + '\'' +
                ", recommendedHotels=" + recommendedHotels +
                ", averagePrice=" + averagePrice +
                ", averageRating=" + averageRating +
                ", preferredRoomType='" + preferredRoomType + '\'' +
                ", suggestionReason='" + suggestionReason + '\'' +
                ", confidenceScore=" + confidenceScore +
                ", timestamp='" + timestamp + '\'' +
                '}';
    }
} 